# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HTN17' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HTN17
  pod 'Alamofire', '~> 4.3'
  pod 'SwiftyJSON'
  pod 'SDWebImage', '~> 3.8'
end
